package org.example.hbank.api.util

object Privileges {

    const val PRIVILEGE_ACCOUNT_READ = "PRIVILEGE::ACCOUNT::READ"
    const val PRIVILEGE_ACCOUNT_WRITE = "PRIVILEGE::ACCOUNT::WRITE"
    const val PRIVILEGE_ADDRESS_READ = "PRIVILEGE::ADDRESS::READ"
    const val PRIVILEGE_ADDRESS_WRITE = "PRIVILEGE::ADDRESS::WRITE"
    const val PRIVILEGE_CUSTOMER_READ = "PRIVILEGE::CUSTOMER::READ"
    const val PRIVILEGE_CUSTOMER_WRITE = "PRIVILEGE::CUSTOMER::WRITE"
    const val PRIVILEGE_TRANSACTION_READ = "PRIVILEGE::TRANSACTION::READ"
    const val PRIVILEGE_TRANSACTION_WRITE = "PRIVILEGE::TRANSACTION::WRITE"
    const val PRIVILEGE_USER_READ = "PRIVILEGE::USER::READ"
    const val PRIVILEGE_USER_WRITE = "PRIVILEGE::USER::WRITE"

    fun getAllPrivileges(): String = listOf(
        PRIVILEGE_ACCOUNT_READ,
        PRIVILEGE_ACCOUNT_WRITE,
        PRIVILEGE_ADDRESS_READ,
        PRIVILEGE_ADDRESS_WRITE,
        PRIVILEGE_CUSTOMER_READ,
        PRIVILEGE_CUSTOMER_WRITE,
        PRIVILEGE_TRANSACTION_READ,
        PRIVILEGE_TRANSACTION_WRITE,
        PRIVILEGE_USER_READ,
        PRIVILEGE_USER_WRITE
    ).joinToString()
}
